name: Build and Deploy

on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Hugo
        run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
          mv hugo $HOME/hugo
          rm -rf site/themes/hugo-coder
        env:
          HUGO_VERSION: 0.91.2
      - name: Hugo Themes
        working-directory: ./site/themes/
        run: git clone https://github.com/arifakkermans/hugo-coder
      - name: Hugo Build
        working-directory: ./site
        run: $HOME/hugo -v
      - name: Deploy to S3
        working-directory: ./site
        if: github.ref == 'refs/heads/main'
        run: $HOME/hugo -v deploy --maxDeletes -1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
